server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servicio-estudiante
          uri: lb://servicio-estudiante
          predicates:
            - Path=/estudiantes/**
        - id: servicio-libro
          uri: lb://servicio-libro
          predicates:
            - Path=/libros/**
        - id: servicio-prestamo
          uri: lb://servicio-prestamo
          predicates:
            - Path=/prestamos/**